// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOEM4iQRv0iRVOIGO9Ke6PSLi5W_E32GU',
    appId: '1:775196988215:web:8f0044cb21bfa6fce600b2',
    messagingSenderId: '775196988215',
    projectId: 'flutternotification-b568e',
    authDomain: 'flutternotification-b568e.firebaseapp.com',
    storageBucket: 'flutternotification-b568e.appspot.com',
    measurementId: 'G-7D29H69X58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnp99uQtYP-rJYSq9Ug106iyh7QqvpwiY',
    appId: '1:775196988215:android:91f1ff3d6256665de600b2',
    messagingSenderId: '775196988215',
    projectId: 'flutternotification-b568e',
    storageBucket: 'flutternotification-b568e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiC2X7SPpGtJ0657GLyeEX1p8zQ_jfPno',
    appId: '1:775196988215:ios:427255c0347dc091e600b2',
    messagingSenderId: '775196988215',
    projectId: 'flutternotification-b568e',
    storageBucket: 'flutternotification-b568e.appspot.com',
    iosBundleId: 'com.example.homeIotDevice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOEM4iQRv0iRVOIGO9Ke6PSLi5W_E32GU',
    appId: '1:775196988215:web:7ba5c923d6a6c254e600b2',
    messagingSenderId: '775196988215',
    projectId: 'flutternotification-b568e',
    authDomain: 'flutternotification-b568e.firebaseapp.com',
    storageBucket: 'flutternotification-b568e.appspot.com',
    measurementId: 'G-9QGNTDY5XD',
  );
}
